# .goreleaser.yaml configuration for GoReleaser v2
# See https://goreleaser.com/customization/ for detailed documentation

version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    # Run tests to catch regressions before release
    - go test ./...
    # Optional: Uncomment to include docs.zip for Packer.io
    #- make ci-release-docs
    # Check plugin compatibility with required Packer SDK version
    - make plugin-check

builds:
  - id: plugin-check
    binary: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.VersionPrerelease=
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

  - binary: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.VersionPrerelease=
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    format: zip
    files:
      - none*
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - --batch
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"

release:
  # Uncomment to create a draft release for manual review
  # draft: true
  # Optional: Uncomment to include docs.zip for Packer.io
  # extra_files:
  #   - glob: ./docs.zip
  github:
    owner: denisslapchenko
    name: packer-plugin-ionoscloud

changelog:
  disable: true
