---
name: CI

on:
  pull_request:  # no need for 'push'; all pushes (to master) are PR-ed
    branches:
      - '**'
    tags-ignore:
      - 'v*'  # Don't run CI tests on release tags

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build
        run: make build
      - name: Unit tests
        run: make test
      - name: Acceptance tests
        run: |
          make testacc
        env:
          IONOS_USERNAME: ${{ secrets.IONOS_USERNAME }}
          IONOS_PASSWORD: ${{ secrets.IONOS_PASSWORD }}
